apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims-dns
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels: { app: ims-dns }
  template:
    metadata:
      labels: { app: ims-dns }
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{ "name": "sbi-network", "ips": [ "10.10.10.60/24" ] }]
    spec:
      containers:
        - name: dns
          image: ghcr.io/ygzaydn/5glab-ims-dns:latest
          command: ["/bin/bash", "/mnt/dns/dns_init.sh"]
          envFrom:
            - configMapRef: { name: ims-env }
          env:
            - name: NRF_IP
              value: "10.10.10.10"
            - name: SCP_IP
              value: "10.10.10.11"
            # Placeholder values
            - name: SMSC_IP
              value: "10.10.10.65"
            - name: IBCF_IP
              value: "10.10.10.66"
            - name: PCRF_IP
              value: "10.10.10.67"
            - name: OSMOEPDG_IP
              value: "10.10.10.68"
            - name: ENTITLEMENT_SERVER_IP
              value: "10.10.10.69"
            - name: DOCKER_HOST_IP
              value: "10.10.10.70"
          volumeMounts:
            - name: dns-mnt
              mountPath: /mnt/dns
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
      volumes:
        - name: dns-mnt
          configMap:
            name: ims-dns-files
            defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: ims-dns
  namespace: open5gs
spec:
  type: ClusterIP
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    app: ims-dns
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ims-dns
  namespace: open5gs
subsets:
  - addresses:
      - ip: 10.10.10.60
    ports:
      - name: dns-udp
        port: 53
        protocol: UDP
      - name: dns-tcp
        port: 53
        protocol: TCP
