apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcscf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcscf
  template:
    metadata:
      labels:
        app: pcscf
      annotations:
        # Multus IP
        k8s.v1.cni.cncf.io/networks: |
          [{ "name": "sbi-network", "ips": [ "10.10.10.61/24" ] }]
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers: [ "10.10.10.60" ]
      containers:
        - name: pcscf
          image:  ghcr.io/kamailio/kamailio:5.8.7-noble
          imagePullPolicy: IfNotPresent
          command: ["/mnt/pcscf/pcscf_init.sh"]
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: COMPONENT_NAME
              value: "pcscf"
            - name: DEPLOY_MODE
              value: "5G"
          envFrom:
            - configMapRef:
                name: ims-env
          volumeMounts:
            - name: pcscf-mnt
              mountPath: /mnt/pcscf
      volumes:
        - name: pcscf-mnt
          configMap:
            name: ims-pcscf-files
            defaultMode: 0755
---

apiVersion: v1
kind: Service
metadata:
  name: pcscf
  namespace: open5gs
spec:
  selector:
    app: pcscf
  type: ClusterIP
  ports:
    - name: sip-udp
      port: 5060
      protocol: UDP
      targetPort: 5060
    - name: sip-tcp
      port: 5060
      protocol: TCP
      targetPort: 5060
