apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-config
  namespace: open5gs
data:
  amf.yaml: |-
    logger:
      file:
        path: /opt/open5gs/var/log/open5gs/amf.log

    global:
      max:
        ue: 8192

    amf:
      max:
        ue: 8192
      sbi:
        server:
          - dev: net1
            port: 7777
        client:
          scp:
            - uri: http://scp:7777
        max_num_of_ostreams: 65535
        max_num_of_istreams: 65535
      sctp:
        max_num_of_ostreams: 65535
        max_num_of_istreams: 65535
      ngap:
        server:
          - dev: net1
      metrics:
        server:
          - dev: net1
            port: 9090
      guami:
        - plmn_id:
            mcc: 999
            mnc: 70
          amf_id:
            region: 2
            set: 1
      tai:
        - plmn_id:
            mcc: 999
            mnc: 70
          tac: 1
      plmn_support:
        - plmn_id:
            mcc: 999
            mnc: 70
          s_nssai:
            - sst: 1
              sd: "000001"
            - sst: 2
              sd: "000061"
      security:
        integrity_order: [NIA2, NIA1, NIA0]
        ciphering_order: [NEA0, NEA1, NEA2]
      network_name:
        full: Open5GS
        short: Next
      amf_name: open5gs-amf0
      time:
        t3512:
          value: 540
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name": "sbi-network", "ips": ["10.10.10.12/24"] }]'
      labels:
        app: amf
    spec:
      containers:
      - name: amf
        image: ghcr.io/ygzaydn/5glab-amf:latest
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "4"
            memory: "2Gi"
        command: ["/bin/sh", "-c"]
        args:
          - |
            ulimit -n 65535
            /opt/open5gs/bin/open5gs-amfd -c /opt/open5gs/etc/open5gs/amf.yaml
        env:
        - name: DB_URI
          value: "mongodb://mongodb:27017/open5gs"
        volumeMounts:
        - name: amf-config
          mountPath: /opt/open5gs/etc/open5gs/amf.yaml
          subPath: amf.yaml
        ports:
        - containerPort: 38412
          protocol: SCTP
        - containerPort: 7777
          protocol: TCP
        - containerPort: 9090
          protocol: TCP
      volumes:
      - name: amf-config
        configMap:
          name: amf-config
