apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-config
  namespace: open5gs
data:
  ausf.yaml: |
    logger:
      file:
        path: /opt/open5gs/var/log/open5gs/ausf.log

    global:
      max:
        ue: 8192

    ausf:
      sbi:
        server:
          - address: 10.10.10.15
            port: 7777
        client:
          scp:
            - uri: http://10.10.10.11:7777

    metrics:
      server:
        - address: net1
          port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ausf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ausf
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name": "sbi-network", "ips": ["10.10.10.15/24"] }]'
      labels:
        app: ausf
    spec:
      containers:
      - name: ausf
        image: ghcr.io/ygzaydn/5glab-ausf:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            ulimit -n 65535
            /opt/open5gs/bin/open5gs-ausfd -c /opt/open5gs/etc/open5gs/ausf.yaml
        ports:
        - containerPort: 7777
          name: sbi
        volumeMounts:
        - name: ausf-config
          mountPath: /opt/open5gs/etc/open5gs/ausf.yaml
          subPath: ausf.yaml
      volumes:
      - name: ausf-config
        configMap:
          name: ausf-config
---
apiVersion: v1
kind: Service
metadata:
  name: ausf
  namespace: open5gs
spec:
  clusterIP: None
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ausf
  namespace: open5gs
subsets:
  - addresses:
      - ip: 10.10.10.15
    ports:
      - name: sbi
        port: 7777
      - name: metrics
        port: 9090
