apiVersion: v1
kind: ConfigMap
metadata:
  name: bsf-config
  namespace: open5gs
data:
  bsf.yaml: |
    logger:
      file:
        path: /opt/open5gs/var/log/open5gs/bsf.log

    global:
      max:
        ue: 8192

    bsf:
      sbi:
        server:
          - address: 10.10.10.20
            port: 7777
        client:
          scp:
            - uri: http://10.10.10.11:7777

    metrics:
      server:
        - address: net1
          port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bsf
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name": "sbi-network", "ips": ["10.10.10.20/24"] }]'
      labels:
        app: bsf
    spec:
      containers:
      - name: bsf
        image: ghcr.io/ygzaydn/5glab-bsf:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            ulimit -n 65535
            /opt/open5gs/bin/open5gs-bsfd -c /opt/open5gs/etc/open5gs/bsf.yaml
        ports:
        - containerPort: 7777
          protocol: TCP
        volumeMounts:
        - name: bsf-config
          mountPath: /opt/open5gs/etc/open5gs/bsf.yaml
          subPath: bsf.yaml
      volumes:
      - name: bsf-config
        configMap:
          name: bsf-config
---
apiVersion: v1
kind: Service
metadata:
  name: bsf
  namespace: open5gs
spec:
  clusterIP: None
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Endpoints
metadata:
  name: bsf
  namespace: open5gs
subsets:
  - addresses:
      - ip: 10.10.10.20
    ports:
      - name: sbi
        port: 7777
        protocol: TCP
      - name: metrics
        port: 9090
        protocol: TCP
