apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: open5gs
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        # image: mongo:4.4.10
        image: ghcr.io/ygzaydn/5glab-mongodb:latest
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: open5gs-mongodb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open5gs-mongodb-pvc
  namespace: open5gs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: open5gs
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
