apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-config
  namespace: open5gs
data:
  pcf.yaml: |-
    logger:
      file:
        path: /opt/open5gs/var/log/open5gs/pcf.log

    global:
      max:
        ue: 8192

    pcf:
      sbi:
        server:
          - address: 10.10.10.17
            port: 7777
        client:
          scp:
            - uri: http://10.10.10.11:7777
    metrics:
      server:
        - address: 10.10.10.17
          port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcf
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name": "sbi-network", "ips": ["10.10.10.17/24"] }]'
      labels:
        app: pcf
    spec:
      containers:
      - name: pcf
        image: ghcr.io/ygzaydn/5glab-pcf:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            ulimit -n 65535
            /opt/open5gs/bin/open5gs-pcfd -c /opt/open5gs/etc/open5gs/pcf.yaml
        env:
        - name: DB_URI
          value: "mongodb://mongodb:27017/open5gs"
        ports:
        - containerPort: 7777
          protocol: TCP
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: pcf-config
          mountPath: /opt/open5gs/etc/open5gs/pcf.yaml
          subPath: pcf.yaml
      volumes:
      - name: pcf-config
        configMap:
          name: pcf-config
---
apiVersion: v1
kind: Service
metadata:
  name: pcf
  namespace: open5gs
spec:
  clusterIP: None
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pcf
  namespace: open5gs
subsets:
  - addresses:
      - ip: 10.10.10.17
    ports:
      - name: sbi
        port: 7777
        protocol: TCP
      - name: metrics
        port: 9090
        protocol: TCP
