apiVersion: apps/v1
kind: Deployment
metadata:
  name: scp
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scp
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            { "name": "sbi-network", "ips": ["10.10.10.11/24"] }
          ]
      labels:
        app: scp
    spec:
      containers:
      - name: scp
        image: ghcr.io/ygzaydn/5glab-scp:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Global limitleri en başa ekle
            if ! grep -q "global:" /opt/open5gs/etc/open5gs/scp.yaml; then
              printf "global:\n  max:\n    ue: 8192\n" > /tmp/scp_header.yaml
              cat /opt/open5gs/etc/open5gs/scp.yaml >> /tmp/scp_header.yaml
              mv /tmp/scp_header.yaml /opt/open5gs/etc/open5gs/scp.yaml
            else
              sed -i '/global:/!b;n;n;s/ue: .*/ue: 8192/' /opt/open5gs/etc/open5gs/scp.yaml
            fi

            # SBI Stream limitlerini ekle (Proxy performansı için kritik)
            sed -i '/sbi:/a \    max_num_of_ostreams: 65535\n    max_num_of_istreams: 65535' /opt/open5gs/etc/open5gs/scp.yaml

            # Standart sed işlemleri
            sed -i 's/dev: eth0/dev: net1/g' /opt/open5gs/etc/open5gs/scp.yaml
            sed -i 's/addr: 127.0.0.200/addr: 0.0.0.0/g' /opt/open5gs/etc/open5gs/scp.yaml
            
            ulimit -n 65535
            /opt/open5gs/bin/open5gs-scpd -c /opt/open5gs/etc/open5gs/scp.yaml
        env:
        - name: DB_URI
          value: "mongodb://mongodb:27017/open5gs"
        ports:
        - containerPort: 7777
          name: sbi
---
apiVersion: v1
kind: Service
metadata:
  name: scp
  namespace: open5gs
spec:
  clusterIP: None
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Endpoints
metadata:
  name: scp
  namespace: open5gs
subsets:
  - addresses:
      - ip: 10.10.10.11
    ports:
      - name: sbi
        port: 7777
        protocol: TCP
      - name: metrics
        port: 9090
        protocol: TCP
