apiVersion: v1
kind: ConfigMap
metadata:
  name: smf-config
  namespace: open5gs
data:
  smf.yaml: |-
    logger:
      file:
        path: /opt/open5gs/var/log/open5gs/smf.log

    global:
      max:
        ue: 8192

    smf:
      p-cscf:
        - 10.3.0.27
      sbi:
        server:
          - dev: net1
            port: 7777
        client:
          scp:
            - uri: http://scp:7777
        max_num_of_ostreams: 65535
        max_num_of_istreams: 65535
      pfcp:
        server:
          - dev: net1
        client:
          upf:
            - address: upf
        max_num_of_ostreams: 65535
        max_num_of_istreams: 65535
      gtpc:
        server:
          - dev: net1
      gtpu:
        server:
          - dev: net1
      metrics:
        server:
          - dev: net1
            port: 9090
      session:
        - subnet: 10.45.0.1/16
          dnn: internet
        - subnet: 10.46.0.1/16
          dnn: ims
        - subnet: 10.47.0.1/16
          dnn: internet-s2
        - subnet: 10.48.0.1/16
          dnn: ims-s2
      dns:
        - 8.8.8.8
        - 8.8.4.4
      mtu: 1400
      ctf:
        enabled: auto
      freeDiameter: /opt/open5gs/etc/freeDiameter/smf.conf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            { "name": "sbi-network", "ips": ["10.10.10.13/24"] }
          ]
      labels:
        app: smf
    spec:
      containers:
        - name: smf
          image: ghcr.io/ygzaydn/5glab-smf:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              ulimit -n 65535
              sed -i 's|TLS_Cred = .*|TLS_Cred = "/opt/open5gs/etc/freeDiameter/smf.cert.pem", "/opt/open5gs/etc/freeDiameter/smf.key.pem";|g' /opt/open5gs/etc/freeDiameter/smf.conf
              sed -i 's|TLS_CA = .*|TLS_CA = "/opt/open5gs/etc/freeDiameter/cacert.pem";|g' /opt/open5gs/etc/freeDiameter/smf.conf
              sed -i 's/^ConnectPeer = "pcrf.gradiant"/#ConnectPeer = "pcrf.gradiant"/g' /opt/open5gs/etc/freeDiameter/smf.conf
              /opt/open5gs/bin/open5gs-smfd -c /opt/open5gs/etc/open5gs/smf.yaml
          volumeMounts:
            - name: smf-config
              mountPath: /opt/open5gs/etc/open5gs/smf.yaml
              subPath: smf.yaml
          ports:
            - containerPort: 7777
              protocol: TCP
            - containerPort: 8805
              protocol: UDP
            - containerPort: 9090
              protocol: TCP
      volumes:
        - name: smf-config
          configMap:
            name: smf-config
