
apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-config
  namespace: open5gs
data:
  udm.yaml: |-
    logger:
      file:
        path: /opt/open5gs/var/log/open5gs/udm.log

    global:
      max:
        ue: 8192

    udm:
      hnet:
        - id: 1
          scheme: 1
          key: "@sysconfdir@/open5gs/hnet/curve25519-1.key"
        - id: 2
          scheme: 2
          key: "@sysconfdir@/open5gs/hnet/secp256r1-2.key"
        - id: 3
          scheme: 1
          key: "@sysconfdir@/open5gs/hnet/curve25519-3.key"
        - id: 4
          scheme: 2
          key: "@sysconfdir@/open5gs/hnet/secp256r1-4.key"
        - id: 5
          scheme: 1
          key: "@sysconfdir@/open5gs/hnet/curve25519-5.key"
        - id: 6
          scheme: 2
          key: "@sysconfdir@/open5gs/hnet/secp256r1-6.key"
      sbi:
        server:
          - address: 10.10.10.14
            port: 7777
        client:
          scp:
            - uri: http://10.10.10.11:7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udm
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[ { "name": "sbi-network", "ips": ["10.10.10.14/24"] } ]'
      labels:
        app: udm
    spec:
      containers:
      - name: udm
        image: ghcr.io/ygzaydn/5glab-udm:latest
        command: ["/bin/sh", "-c"]
        args:
          - |

            ulimit -n 65535
            /opt/open5gs/bin/open5gs-udmd -c /opt/open5gs/etc/open5gs/udm.yaml
        env:
        - name: DB_URI
          value: "mongodb://mongodb:27017/open5gs"
        ports:
        - containerPort: 7777
        volumeMounts:
          - name: udm-config
            mountPath: /opt/open5gs/etc/open5gs/udm.yaml
            subPath: udm.yaml
      volumes:
        - name: udm-config
          configMap:
            name: udm-config

---
apiVersion: v1
kind: Service
metadata:
  name: udm
  namespace: open5gs
spec:
  clusterIP: None
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Endpoints
metadata:
  name: udm
  namespace: open5gs
subsets:
  - addresses:
      - ip: 10.10.10.14
    ports:
      - name: sbi
        port: 7777
        protocol: TCP
      - name: metrics
        port: 9090
        protocol: TCP
