apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udr
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "sbi-network", "ips": ["10.10.10.18/24"] }
        ]'
      labels:
        app: udr
    spec:
      containers:
      - name: udr
        image: ghcr.io/ygzaydn/5glab-udr:latest
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "4"
            memory: "1Gi"
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Global limitleri en başa ekle
            if ! grep -q "global:" /opt/open5gs/etc/open5gs/udr.yaml; then
              printf "global:\n  max:\n    ue: 8192\n" > /tmp/udr_header.yaml
              cat /opt/open5gs/etc/open5gs/udr.yaml >> /tmp/udr_header.yaml
              mv /tmp/udr_header.yaml /opt/open5gs/etc/open5gs/udr.yaml
            else
              sed -i '/global:/!b;n;n;s/ue: .*/ue: 8192/' /opt/open5gs/etc/open5gs/udr.yaml
            fi

            # SBI Stream limitlerini ekle
            sed -i '/sbi:/a \    max_num_of_ostreams: 65535\n    max_num_of_istreams: 65535' /opt/open5gs/etc/open5gs/udr.yaml

            # Standart sed işlemleri
            sed -i 's/dev: eth0/dev: net1/g' /opt/open5gs/etc/open5gs/udr.yaml
            sed -i 's/addr: 127.0.0.6/addr: 0.0.0.0/g' /opt/open5gs/etc/open5gs/udr.yaml
            
            ulimit -n 65535
            /opt/open5gs/bin/open5gs-udrd -c /opt/open5gs/etc/open5gs/udr.yaml
        env:
        - name: DB_URI
          value: "mongodb://mongodb:27017/open5gs"
        ports:
        - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: udr
  namespace: open5gs
spec:
  clusterIP: None
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Endpoints
metadata:
  name: udr
  namespace: open5gs
subsets:
  - addresses:
      - ip: 10.10.10.18
    ports:
      - name: sbi
        port: 7777
        protocol: TCP
      - name: metrics
        port: 9090
        protocol: TCP
