apiVersion: v1
kind: ConfigMap
metadata:
  name: upf-config
  namespace: open5gs
data:
  upf.yaml: |-
    logger:
      file:
        path: /opt/open5gs/var/log/open5gs/upf.log
    upf:
      pfcp:
        server:
          - dev: net1
      gtpu:
        server:
          - dev: net1
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
          dnn: internet
          dev: ogstun
        - subnet: 10.46.0.0/16
          gateway: 10.46.0.1
          dnn: ims
          dev: ogstun3
        - subnet: 10.47.0.0/16
          gateway: 10.47.0.1
          dnn: internet-s2
          dev: ogstun2
        - subnet: 10.48.0.0/16
          gateway: 10.48.0.1
          dnn: ims-s2
          dev: ogstun4
      metrics:
        server:
          - dev: net1
            port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            { "name": "sbi-network", "ips": ["10.10.10.21/24"] }
          ]
      labels:
        app: upf
    spec:
      containers:
        - name: upf
          # image: gradiant/open5gs:2.7.6
          image: ghcr.io/ygzaydn/5glab-upf:latest
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
            capabilities:
              add: ["NET_ADMIN", "NET_RAW", "SYS_ADMIN"]
            seccompProfile:
              type: Unconfined
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
            - name: upf-config
              mountPath: /opt/open5gs/etc/open5gs/upf.yaml
              subPath: upf.yaml
          command: ["/bin/sh", "-c"]
          args:
            - |
              ls -l /dev/net/tun || true

              sysctl -w net.ipv4.ip_forward=1 || true

              ip tuntap add name ogstun mode tun || true
              ip addr add 10.45.0.1/16 dev ogstun || true
              ip link set ogstun up || true

              ip tuntap add name ogstun3 mode tun || true
              ip addr add 10.46.0.1/16 dev ogstun3 || true
              ip link set ogstun3 up || true

              ip tuntap add name ogstun2 mode tun || true
              ip addr add 10.47.0.1/16 dev ogstun2 || true
              ip link set ogstun2 up || true

              ip tuntap add name ogstun4 mode tun || true
              ip addr add 10.48.0.1/16 dev ogstun4 || true
              ip link set ogstun4 up || true

              iptables -t nat -A POSTROUTING -s 10.45.0.0/16 ! -o ogstun -j MASQUERADE || true
              iptables -t nat -A POSTROUTING -s 10.46.0.0/16 ! -o ogstun3 -j MASQUERADE || true
              iptables -t nat -A POSTROUTING -s 10.47.0.0/16 ! -o ogstun2 -j MASQUERADE || true
              iptables -t nat -A POSTROUTING -s 10.48.0.0/16 ! -o ogstun4 -j MASQUERADE || true

              /opt/open5gs/bin/open5gs-upfd -c /opt/open5gs/etc/open5gs/upf.yaml
          ports:
            - containerPort: 8805
              protocol: UDP
            - containerPort: 2152
              protocol: UDP
            - containerPort: 9090
              protocol: TCP
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: upf-config
          configMap:
            name: upf-config
---
apiVersion: v1
kind: Service
metadata:
  name: upf
  namespace: open5gs
spec:
  clusterIP: None
  ports:
    - name: n4
      protocol: UDP
      port: 8805
      targetPort: 8805
    - name: n3
      protocol: UDP
      port: 2152
      targetPort: 2152
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Endpoints
metadata:
  name: upf
  namespace: open5gs
subsets:
  - addresses:
      - ip: 10.10.10.21
    ports:
      - name: n4
        port: 8805
        protocol: UDP
      - name: n3
        port: 2152
        protocol: UDP
      - name: metrics
        port: 9090
        protocol: TCP

